#!/usr/bin/env node
// Generates INDEX.md — a complete, grouped map of every artifact in the toolbox,
// so the landing page is one click from anything. Zero dependencies.
//
//   node scripts/generate-index.mjs          write INDEX.md   (alias: npm run index)
//   node scripts/generate-index.mjs check     exit non-zero if INDEX.md is stale (CI)
//
// The index is derived from the file tree + each file's title/first-comment, so it
// stays correct automatically as content is added. Do not hand-edit INDEX.md.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname, relative, resolve, sep, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const INDEX = join(ROOT, "INDEX.md");

// Artifact folders, in the order they appear in the index.
const SECTIONS = ["references", "resources", "snippets", "configs", "prompts", "checklists", "playbooks", "scripts"];
const IGNORE = new Set([".git", "node_modules", "site"]);

const posix = (p) => p.split(sep).join("/");

async function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (IGNORE.has(e.name)) continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

// Terse one-line summary: strip links, emphasis, and code formatting, then cap length.
function clean(s) {
  const t = s.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/[`*_]/g, "").trim();
  if (t.length <= 160) return t;
  const cut = t.slice(0, 160);
  return cut.slice(0, cut.lastIndexOf(" ")).trimEnd() + "…";
}

// First prose line of a Markdown file, after the H1: a blockquote, a `**TL;DR:**`
// lead, or a plain paragraph — whichever comes first. (References lead with TL;DR,
// playbooks/resources lead with a blockquote.)
function firstProse(content) {
  let afterTitle = false;
  for (const raw of content.split(/\r?\n/)) {
    const l = raw.trim();
    if (/^#\s+/.test(l)) { afterTitle = true; continue; }
    if (!afterTitle || !l) continue;
    if (/^#{1,6}\s/.test(l)) break; // next heading with no prose between
    return l.replace(/^>\s?/, "").replace(/^\*\*TL;DR:\*\*\s*/i, "");
  }
  return "";
}

// Returns { title, desc }. Title from the first H1 (Markdown only); desc from the
// first prose line (Markdown) or the first comment line (code/config).
async function summarize(full) {
  let content;
  try {
    content = await readFile(full, "utf8");
  } catch {
    return { title: null, desc: "" };
  }
  if (extname(full) === ".md") {
    const title = content.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? null;
    return { title, desc: clean(firstProse(content)) };
  }
  for (const raw of content.split(/\r?\n/).slice(0, 8)) {
    const l = raw.trim();
    if (!l || l.startsWith("#!")) continue; // blank or shebang
    if (l.startsWith("#")) return { title: null, desc: clean(l.replace(/^#+\s?/, "")) };
    if (l.startsWith("//")) return { title: null, desc: clean(l.replace(/^\/\/+\s?/, "")) };
    break; // first real line isn't a comment
  }
  return { title: null, desc: "" };
}

function entryLine(full, sum, text) {
  const path = posix(relative(ROOT, full));
  return `- [${text}](${path})${sum.desc ? ` — ${sum.desc}` : ""}\n`;
}

async function build() {
  let md =
    "# Index\n\n" +
    "> Complete map of every artifact in the toolbox — one page, one click to anything. " +
    "Auto-generated by [scripts/generate-index.mjs](scripts/generate-index.mjs); do not hand-edit " +
    "(run `npm run index`). CI fails if it drifts from the file tree.\n\n" +
    "**Start here:** [README.md](README.md) — what this is · [ARTIFACTS.md](ARTIFACTS.md) — where things go.\n";

  for (const section of SECTIONS) {
    const secDir = join(ROOT, section);
    const files = await walk(secDir);
    if (!files.length) continue;

    const secReadme = join(secDir, "README.md");
    const secSum = files.includes(secReadme) ? await summarize(secReadme) : { desc: "" };
    md += `\n## \`${section}/\`\n`;
    if (secSum.desc) md += `\n${secSum.desc}\n`;

    // Group by immediate subdirectory (the shard); "" = files directly in the section.
    const groups = new Map();
    for (const f of files) {
      if (f === secReadme) continue;
      const rel = posix(relative(secDir, f));
      const i = rel.indexOf("/");
      const shard = i === -1 ? "" : rel.slice(0, i);
      (groups.get(shard) ?? groups.set(shard, []).get(shard)).push(f);
    }

    const shards = [...groups.keys()].sort((a, b) =>
      a === "" ? -1 : b === "" ? 1 : a.localeCompare(b),
    );

    for (const shard of shards) {
      const groupFiles = groups.get(shard).sort();
      let shardReadme = null;
      if (shard) {
        shardReadme = join(secDir, shard, "README.md");
        if (groupFiles.includes(shardReadme)) {
          const s = await summarize(shardReadme);
          md += `\n### [${s.title ?? `${section}/${shard}/`}](${posix(relative(ROOT, shardReadme))})\n`;
          if (s.desc) md += `\n${s.desc}\n`;
        } else {
          md += `\n### \`${section}/${shard}/\`\n`;
          shardReadme = null;
        }
        md += "\n";
      }
      for (const f of groupFiles) {
        if (f === shardReadme) continue;
        const sum = await summarize(f);
        md += entryLine(f, sum, sum.title ?? basename(f));
      }
    }
  }
  return md;
}

const mode = process.argv[2];
const generated = await build();

if (mode === "check") {
  let existing = null;
  try {
    existing = await readFile(INDEX, "utf8");
  } catch {
    /* missing */
  }
  const norm = (s) => (s ?? "").replace(/\r\n/g, "\n");
  if (norm(existing) !== norm(generated)) {
    console.error("✖ INDEX.md is out of date. Run `npm run index` and commit the result.");
    process.exit(1);
  }
  console.log("✓ INDEX.md is up to date.");
} else {
  await writeFile(INDEX, generated);
  console.log("✓ Wrote INDEX.md");
}
